name: CI
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
defaults:
  run:
    shell: pwsh
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows
          - os: ubuntu-latest
            name: Linux
      fail-fast: false
    steps:
      - name: Check for secrets
        env:
          SECRETS_AVAILABLE: ${{ secrets.SECRETS_AVAILABLE }}
        run: exit $(If ($env:SECRETS_AVAILABLE -eq 'true') { 0 } Else { 1 })
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.x
      - name: Setup Azure Functions Core Tools - Windows
        if: runner.os == 'Windows'
        run: |
          choco install azure-functions-core-tools
          echo "PathToFuncExe=C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\func.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Setup Azure Functions Core Tools - Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install azure-functions-core-tools -y
          echo "PathToFuncExe=func" >> $GITHUB_ENV
        shell: bash
      - name: Fix Azure Functions Core Tools permissions - Linux
        if: runner.os == 'Linux'
        run: sudo chmod +x /usr/lib/azure-functions-core-tools/in-proc8/func
      - name: Build
        run: dotnet build src --configuration Release
      - name: Upload packages
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: NuGet packages
          path: nugets/
          retention-days: 7
      - name: Azure login
        uses: azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_ACI_CREDENTIALS }}
      - name: Setup Azure Service Bus
        uses: Particular/setup-azureservicebus-action@v2.0.0
        with:
          connection-string-name: AzureWebJobsServiceBus
          azure-credentials: ${{ secrets.AZURE_ACI_CREDENTIALS }}
          tag: ASBFunctions
      - name: Run tests
        uses: Particular/run-tests-action@v1.7.0
